version: '3.8'

services:
  apache:
    build: .
    container_name: apache
    ports:
      - "80:80"
    volumes:
      - ./webapp:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

