name: Deploy LAMP App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Run Ansible on EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install ansible -y

      - name: Create SSH key file
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Run Ansible Playbook
        run: |
          ansible-playbook ansible/playbook.yml -i ansible/inventory
        env:
          ANSIBLE_HOST_KEY_CHECKING: false

